# Generated by Django 5.2.8 on 2025-12-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('case_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('anonymous', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
